import {validateAnswer} from '@/lib/citations';
import {env} from 'cloudflare:workers';
import {originCheck,member,body,HttpError,failure} from '@/lib/auth';
import {getEvidence,db,audit} from '@/lib/data';
import {policy,toolspec,executeTool,answerSchemaForSources} from '@/lib/adviser';
async function consume(key:string,max:number){const bucket=Math.floor(Date.now()/3600000);const r=await db().prepare('INSERT INTO rate_limits (user_id,window,count) VALUES (?,?,1) ON CONFLICT(user_id) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END,window=excluded.window RETURNING count').bind(key,bucket).first<any>();if(r.count>max)throw new HttpError(429,'Hourly question limit reached. Please return later.');}
export async function POST(req:Request){let userId='';let tokens=0;try{originCheck(req);const u=await member();userId=u.userId;const b=await body(req);if(typeof b.question!=='string'||b.question.trim().length<3||b.question.length>2000)throw new HttpError(400,'Use a question between 3 and 2000 characters.');const settings=env as any;if(!settings.OPENAI_API_KEY)throw new HttpError(503,'The AI adviser is awaiting its hosted OpenAI credential. Evidence and calculations remain available.');await consume(u.userId,10);await consume('__global__',100);const e=await getEvidence();const countries=['USA','CHN','SGP'].filter((c,n)=>new RegExp([`US|United States|America`,`China|Chinese`,`Singapore`][n],'i').test(b.question));const metrics=e.metrics.filter((m:any)=>countries.length===0||countries.includes(m.country_id));
const input:any[]=[{role:'user',content:JSON.stringify({question:b.question,current_design:e.design,claims:e.claims,metrics,sources:e.sources})}];
for(let turn=0;turn<3;turn++){
const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${settings.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:settings.OPENAI_MODEL||'gpt-4.1-mini',store:false,instructions:policy,input,tools:toolspec,tool_choice:turn===2?'none':'auto',max_output_tokens:1600,text:{format:{type:'json_schema',name:'grounded_answer',strict:true,schema:answerSchemaForSources(e.sources.map((s:any)=>s.id))}}}),signal:AbortSignal.timeout(35000)});
if(!r.ok)throw new HttpError(502,'The AI service could not complete this request. No substitute answer was generated.');const result:any=await r.json();tokens+=result.usage?.total_tokens??0;const calls=(result.output??[]).filter((x:any)=>x.type==='function_call');if(calls.length){if(calls.length>5)throw Error('Too many tools');input.push(...result.output);for(const c of calls){let value;try{value=await executeTool(c.name,JSON.parse(c.arguments),e)}catch{value={error:'Requested tool data unavailable. Identify the evidence gap.'}}input.push({type:'function_call_output',call_id:c.call_id,output:JSON.stringify(value)});}continue;}
const raw=(result.output??[]).flatMap((x:any)=>x.content??[]).filter((x:any)=>x.type==='output_text').map((x:any)=>x.text).join('');const answer=validateAnswer(JSON.parse(raw),new Set(e.sources.map((x:any)=>x.id)));await audit(u.userId,'ai_usage',JSON.stringify({tokens,model:settings.OPENAI_MODEL||'gpt-4.1-mini',status:'success'}));return Response.json({...answer,sources:e.sources.filter((s:any)=>answer.citations.includes(s.id)),tokens,designUpdatedAt:e.design.updated_at});}
throw Error('Tool limit exceeded');}catch(e){if(userId&&tokens)await audit(userId,'ai_usage',JSON.stringify({tokens,status:'failed'})).catch(()=>{});return failure(e)}}
