import {env} from 'cloudflare:workers';
import {sources,countries,metrics,claims,accessed} from './seed';
import {defaults,type Inputs,validateInputs} from './model';
export function db(){if(!env.DB)throw Error('Evidence storage is temporarily unavailable.');return env.DB;}
export async function seed(){const d=db();if(await d.prepare('SELECT id FROM designs WHERE id=1').first())return;const statements=[];
for(const s of sources)statements.push(d.prepare('INSERT OR IGNORE INTO sources (id,publisher,title,url,source_type,publication_date,accessed_at) VALUES (?,?,?,?,?,?,?)').bind(s.id,s.publisher,s.title,s.url,s.source_type,s.publication_date,s.accessed_at));
for(const c of countries)statements.push(d.prepare('INSERT OR IGNORE INTO countries (id,name,region) VALUES (?,?,?)').bind(c.id,c.name,c.region));
statements.push(d.prepare('INSERT OR IGNORE INTO designs (id,selected_country_id,inputs_json,design_summary,updated_at) VALUES (1,?,?,?,?)').bind('USA',JSON.stringify(defaults),'Lease first; conditional Massachusetts 6.25 MW option only after demand and grid gates.',accessed));
for(const m of metrics)statements.push(d.prepare('INSERT OR IGNORE INTO metrics (country_id,metric_name,value,unit,reporting_period,source_id,retrieved_at,confidence,notes) VALUES (?,?,?,?,?,?,?,?,?)').bind(m.country_id,m.metric_name,m.value,m.unit,m.reporting_period,m.source_id,accessed,m.confidence,m.notes));
for(const c of claims)statements.push(d.prepare('INSERT OR IGNORE INTO design_claims (id,design_id,claim_text,claim_type,source_id,status) VALUES (?,1,?,?,?,?)').bind(c.id,c.claim_text,c.claim_type,c.source_id,c.status));
await d.batch(statements);}
export async function getEvidence(){await seed();const d=db();const [c,m,s,q,design]=await Promise.all([d.prepare('SELECT * FROM countries ORDER BY id').all(),d.prepare('SELECT * FROM metrics ORDER BY retrieved_at DESC,id DESC').all(),d.prepare('SELECT * FROM sources ORDER BY id').all(),d.prepare('SELECT * FROM design_claims ORDER BY id').all(),d.prepare('SELECT * FROM designs WHERE id=1').first<any>()]);const seen=new Set<string>();const latest=m.results.filter((x:any)=>{const key=x.country_id+x.metric_name+x.reporting_period;if(seen.has(key))return false;seen.add(key);return true;});return{countries:c.results,metrics:latest,sources:s.results,claims:q.results,design:{...design,inputs:JSON.parse(design.inputs_json)}};}
export async function saveDesign(inputs:Inputs,userId:string,version:string){validateInputs(inputs);const r=await db().prepare('UPDATE designs SET inputs_json=?,updated_at=? WHERE id=1 AND updated_at=?').bind(JSON.stringify(inputs),new Date().toISOString(),version).run();if(!r.meta.changes)throw Error('The saved design changed. Reload before saving.');await audit(userId,'design','Saved design assumptions');}
export async function audit(userId:string,kind:string,detail:string){await db().prepare('INSERT INTO events (user_id,kind,detail,created_at) VALUES (?,?,?,?)').bind(userId,kind,detail,new Date().toISOString()).run();}
