export const accessed='2026-10-05T22:55:00Z';
export const sources=[
{id:'S1',publisher:'US Department of Energy / LBNL',title:'2024 release: US data center electricity demand',url:'https://www.energy.gov/articles/doe-releases-new-report-evaluating-increase-electricity-demand-data-centers',source_type:'official_report',publication_date:'2024-12-20',accessed_at:accessed},
{id:'S2',publisher:'National Bureau of Statistics of China',title:'2024 Statistical Communiqué',url:'https://www.stats.gov.cn/english/PressRelease/202502/t20250228_1958822.html',source_type:'official_statistics',publication_date:'2025-02-28',accessed_at:accessed},
{id:'S3',publisher:'Energy Market Authority, Singapore',title:'Singapore Energy Statistics: Energy Transformation',url:'https://www.ema.gov.sg/resources/singapore-energy-statistics/chapter2',source_type:'official_statistics',publication_date:null,accessed_at:accessed},
{id:'S4',publisher:'US Energy Information Administration',title:'US energy facts: 2024 data and statistics',url:'https://www.eia.gov/energyexplained/us-energy-facts/data-and-statistics.php',source_type:'official_statistics',publication_date:null,accessed_at:accessed},
{id:'S5',publisher:'World Bank, World Development Indicators',title:'Renewable electricity output (% of total) — historical 2015 comparison',url:'https://api.worldbank.org/v2/country/USA;CHN;SGP/indicator/EG.ELC.RNEW.ZS?format=json&date=2015&per_page=100',source_type:'external_api',publication_date:null,accessed_at:accessed},
{id:'S6',publisher:'NVIDIA',title:'DGX H100/H200 system user guide',url:'https://docs.nvidia.com/dgx/dgxh100-user-guide/introduction-to-dgxh100.html',source_type:'manufacturer_documentation',publication_date:null,accessed_at:accessed}];
export const countries=[{id:'USA',name:'United States',region:'Massachusetts — candidate only'},{id:'CHN',name:'China',region:'Shanghai — comparison candidate'},{id:'SGP',name:'Singapore',region:'Singapore — comparison candidate'}];
export const metrics=[
{country_id:'USA',metric_name:'Data center electricity use',value:176,unit:'TWh',reporting_period:'2023',source_id:'S1',confidence:'Published estimate',notes:'Historical estimate from the December 2024 report, not a current inventory or site commitment.'},
{country_id:'USA',metric_name:'National electricity generation',value:4300,unit:'TWh',reporting_period:'2024',source_id:'S4',confidence:'Official rounded statistics',notes:'National electricity generation; not available capacity.'},
{country_id:'USA',metric_name:'Natural gas generation share',value:43,unit:'%',reporting_period:'2024',source_id:'S4',confidence:'Official rounded statistics',notes:'National annual average; not an hourly site supply mix.'},
{country_id:'USA',metric_name:'Renewable generation share',value:23,unit:'%',reporting_period:'2024',source_id:'S4',confidence:'Official rounded statistics',notes:'Rounded national share; definitions differ from the historical World Bank series.'},
{country_id:'CHN',metric_name:'National electricity generation',value:10086.88,unit:'TWh',reporting_period:'2024',source_id:'S2',confidence:'Official preliminary statistics',notes:'Converted from 100868.8 hundred-million kWh. Broader scope than industrial enterprises above designated size.'},
{country_id:'CHN',metric_name:'Thermal electricity generation',value:6374.26,unit:'TWh',reporting_period:'2024',source_id:'S2',confidence:'Official preliminary statistics',notes:'Thermal includes more than coal. Not a direct natural-gas comparison.'},
{country_id:'SGP',metric_name:'National electricity generation',value:60,unit:'TWh',reporting_period:'2024',source_id:'S3',confidence:'Official rounded statistics',notes:'Gross national output; not the capacity available to this project.'},
{country_id:'SGP',metric_name:'Natural gas generation share',value:94,unit:'%',reporting_period:'2024',source_id:'S3',confidence:'Official statistics',notes:'Annual national fuel mix, not a site-specific carbon or uptime guarantee.'},
{country_id:'SGP',metric_name:'Solar generation share',value:2.1,unit:'%',reporting_period:'2024',source_id:'S3',confidence:'Official statistics',notes:'Solar only; must not be compared as total renewable generation.'},
...([{id:'USA',value:13.6328082889697},{id:'CHN',value:23.8649488788885},{id:'SGP',value:4.17967076556922}].map(c=>({country_id:c.id,metric_name:'Historical renewable electricity share',value:c.value,unit:'%',reporting_period:'2015',source_id:'S5',confidence:'Historical API observation',notes:'Comparable historical series only. The queried 2022 series returned null; do not use 2015 values as current conditions.'}))),
...['USA','CHN','SGP'].flatMap(country_id=>['Site electricity price','Grid connection date','Site water allocation','Current comparable datacenter count','Site hourly carbon intensity'].map(metric_name=>({country_id,metric_name,value:null,unit:metric_name==='Site electricity price'?'USD/kWh':'not established',reporting_period:'Unverified',source_id:'S5',confidence:'Unknown',notes:'No verified site-specific or comparable evidence collected; S5 is a research starting point, not support for a value.'})))];
export const claims=[
{id:'C1',claim_text:'No member has signed a long-term compute commitment and grid cost/date are unknown.',claim_type:'fact',source_id:null,status:'Assignment-provided starting fact'},
{id:'C2',claim_text:'Use 20 MW IT, PUE 1.25 and 8760 hours as the initial full-load baseline; these are design assumptions.',claim_type:'assumption',source_id:null,status:'Assignment baseline'},
{id:'C3',claim_text:'Full-load demand is 25 MW and annual energy is 219 GWh for the baseline. Use the current model for edited inputs.',claim_type:'calculation',source_id:null,status:'Deterministic baseline'},
{id:'C4',claim_text:'Do not approve irreversible 25 MW construction now. Lease while validating demand; retain a conditional 6.25 MW facility option.',claim_type:'design_decision',source_id:null,status:'Conditional recommendation'},
{id:'C5',claim_text:'Singapore reported a 94.0% natural gas share in its 2024 electricity fuel mix.',claim_type:'fact',source_id:'S3',status:'Verified source'},
{id:'C6',claim_text:'The US 2024 DOE release estimated 176 TWh of data center electricity use for 2023.',claim_type:'fact',source_id:'S1',status:'Historical published estimate'},
{id:'C7',claim_text:'Delivered GPU prices, equivalent cloud rental rates, site tariffs, grid upgrades and member demand have not been verified.',claim_type:'unknown',source_id:null,status:'Decision-reversing evidence gap'},
{id:'C8',claim_text:'Massachusetts is the illustrative domestic candidate for a hypothetical US university consortium. This is not a proven globally optimal location.',claim_type:'design_decision',source_id:null,status:'Scenario assumption'},
{id:'C9',claim_text:'Use a generic H100-class equivalent unit for modeling; actual hardware performance, price and availability require quotes and benchmarks in each jurisdiction.',claim_type:'assumption',source_id:'S6',status:'Manufacturer source is context, not validation of price or procurement'},
{id:'C10',claim_text:'99% availability and 90% job efficiency are model assumptions, not a certified service level.',claim_type:'assumption',source_id:null,status:'Unverified targets'}];
