import {sqliteTable,text,integer,real,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:integer('id').primaryKey({autoIncrement:true}),authenticatedUserId:text('authenticated_user_id').notNull().unique(),email:text('email'),role:text('role').notNull().default('viewer'),registeredAt:text('registered_at').notNull()});
export const countries=sqliteTable('countries',{id:text('id').primaryKey(),name:text('name').notNull().unique(),region:text('region')});
export const sources=sqliteTable('sources',{id:text('id').primaryKey(),publisher:text('publisher').notNull(),title:text('title').notNull(),url:text('url').notNull(),sourceType:text('source_type').notNull(),publicationDate:text('publication_date'),accessedAt:text('accessed_at').notNull()});
export const metrics=sqliteTable('metrics',{id:integer('id').primaryKey({autoIncrement:true}),countryId:text('country_id').notNull().references(()=>countries.id),metricName:text('metric_name').notNull(),value:real('value'),unit:text('unit').notNull(),reportingPeriod:text('reporting_period').notNull(),sourceId:text('source_id').notNull().references(()=>sources.id),retrievedAt:text('retrieved_at').notNull(),confidence:text('confidence'),notes:text('notes')},t=>[index('idx_metrics_country_metric').on(t.countryId,t.metricName),uniqueIndex('idx_metrics_observation').on(t.countryId,t.metricName,t.reportingPeriod,t.retrievedAt)]);
export const designs=sqliteTable('designs',{id:integer('id').primaryKey(),selectedCountryId:text('selected_country_id').references(()=>countries.id),inputsJson:text('inputs_json').notNull(),designSummary:text('design_summary').notNull(),updatedAt:text('updated_at').notNull()});
export const claims=sqliteTable('design_claims',{id:text('id').primaryKey(),designId:integer('design_id').notNull().references(()=>designs.id),claimText:text('claim_text').notNull(),claimType:text('claim_type').notNull(),sourceId:text('source_id').references(()=>sources.id),status:text('status').notNull()},t=>[index('idx_claims_design').on(t.designId)]);
export const events=sqliteTable('events',{id:integer('id').primaryKey({autoIncrement:true}),userId:text('user_id').notNull(),kind:text('kind').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_events_user_time').on(t.userId,t.createdAt)]);
export const limits=sqliteTable('rate_limits',{userId:text('user_id').primaryKey(),window:integer('window').notNull(),count:integer('count').notNull()});
